version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=hello_typeorm
    ports:
      - "3306:3306"
    restart: unless-stopped