version: "3.9"

services:
  api_server:
    build: .
    image: api_server
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=hello_typeorm
    ports:
      - "3306:3306"
    restart: unless-stopped